/**
 * @file dmpc_matrices.h
 * @brief Header with data to run the DMPC algorithm.
 *
 * This file is generated automatically and should not be modified.
 *
 * The Hj matrix is already generated by flipping the sign and inverting its
 * diagonal elements, so that Hildreth's algorithm does not require any 
 * divisions.
 *
 */

#ifndef DMPC_MATRICES_H_
#define DMPC_MATRICES_H_

#include "stdint.h"

/* Input constraints */
extern float DMPC_CONFIG_U_MIN[2];
extern float DMPC_CONFIG_U_MAX[2];
extern uint32_t DMPC_CONFIG_U_LIM_IDX[2];

/* State constraints */
extern float DMPC_CONFIG_XM_MIN[2];
extern float DMPC_CONFIG_XM_MAX[2];
extern uint32_t DMPC_CONFIG_XM_LIM_IDX[2];

/* Index of ouputs */
extern uint32_t DMPC_CONFIG_Y_IDX[2];

/*
 * A and B matrices for prediction.
 * A corresponds to model matrix Am.
 * B corresponds to model matrix Bm concatenated with Bd, if Bd exists.
*/
extern float DMPC_M_A[6][6];
extern float DMPC_M_B[6][4];

/*
 * Matrices for QP solvers 
 *
 * The matrices were generated considering the following problem:
 *
 * min (1/2) * DU' * Ej * DU + DU' * Fj
 * DU
 *
 * s.t. M * DU <= gam
 *
 * The (1/2) term in from of DU' * Ej * DU needs to be considered in the QP
 * solver selected, or the solution will appear to be inconsistent.
 * Note that the Fj and gam matrices are usually updated online, while Ej
 * and M are static.
 */
extern float DMPC_M_Ej[8][8];
extern float DMPC_M_Fj[8];
extern float DMPC_M_M[32][8];
extern float DMPC_M_gam[32];

/* Matrices for Hildreth's QP procedure */
extern float DMPC_M_Fj_1[8][2];
extern float DMPC_M_Fj_2[8][8];
extern float DMPC_M_Fx[8][6];
extern float DMPC_M_Kj_1[32][8];
extern float DMPC_M_Hj[32][32];
extern float DMPC_M_DU_1[2][8];
extern float DMPC_M_DU_2[2][32];

#endif /* DMPC_MATRICES_H_ */
