/**
 * @file dmpc_matrices.h
 * @brief Header with data to run the DMPC algorithm.
 *
 * This file is generated automatically and should not be modified.
 *
 * The Hj matrix is already generated by flipping the sign and inverting its
 * diagonal elements, so that Hildreth's algorithm does not require any 
 * divisions.
 *
 */

#ifndef DMPC_MATRICES_H_
#define DMPC_MATRICES_H_

#include "stdint.h"

/* Input constraints */
extern float DMPC_CONFIG_U_MIN[1];
extern float DMPC_CONFIG_U_MAX[1];
extern uint32_t DMPC_CONFIG_U_LIM_IDX[1];

/* State constraints */
extern float DMPC_CONFIG_XM_MIN[1];
extern float DMPC_CONFIG_XM_MAX[1];
extern uint32_t DMPC_CONFIG_XM_LIM_IDX[1];

/* Index of ouputs */
extern uint32_t DMPC_CONFIG_Y_IDX[1];

/*
 * A and B matrices for prediction.
 * A corresponds to model matrix Am.
 * B corresponds to model matrix Bm concatenated with Bd, if Bd exists.
*/
extern float DMPC_M_A[2][2];
extern float DMPC_M_B[2];

/* Optimal Kx and Ky for unconstrained problems */
extern float DMPC_Kx[2];
extern float DMPC_Ky[1];

/*
 * Matrices for QP solvers 
 *
 * The matrices were generated considering the following problem:
 *
 * min (1/2) * DU' * Ej * DU + DU' * Fj
 * DU
 *
 * s.t. M * DU <= gam
 *
 * The (1/2) term in from of DU' * Ej * DU needs to be considered in the QP
 * solver selected, or the solution will appear to be inconsistent.
 * Note that the Fj and gam matrices are usually updated online, while Ej
 * and M are static.
 */
extern float DMPC_M_Ej[4][4];
extern float DMPC_M_Fj[4];
extern float DMPC_M_M[16][4];
extern float DMPC_M_gam[16];

/* Matrices for Hildreth's QP procedure */
extern float DMPC_M_Fj_1[4];
extern float DMPC_M_Fj_2[4][3];
extern float DMPC_M_Fx[4][2];
extern float DMPC_M_Kj_1[16][4];
extern float DMPC_M_Hj[16][16];
extern float DMPC_M_DU_1[4];
extern float DMPC_M_DU_2[16];

#endif /* DMPC_MATRICES_H_ */
