#ifndef WORKSPACE_H
#define WORKSPACE_H

/*
 * This file was autogenerated by OSQP-Python on May 18, 2023 at 15:37:50.
 * 
 * This file contains the prototypes for all the workspace variables needed
 * by OSQP. The actual data is contained inside workspace.c.
 */

#include "types.h"
#include "qdldl_interface.h"

// Data structure prototypes
extern csc Pdata;
extern csc Adata;
extern c_float qdata[8];
extern c_float ldata[16];
extern c_float udata[16];
extern OSQPData data;

// Settings structure prototype
extern OSQPSettings settings;

// Scaling structure prototypes
extern c_float Dscaling[8];
extern c_float Dinvscaling[8];
extern c_float Escaling[16];
extern c_float Einvscaling[16];
extern OSQPScaling scaling;

// Prototypes for linsys_solver structure
extern csc linsys_solver_L;
extern c_float linsys_solver_Dinv[24];
extern c_int linsys_solver_P[24];
extern c_float linsys_solver_bp[24];
extern c_float linsys_solver_sol[24];
extern c_float linsys_solver_rho_inv_vec[16];
extern qdldl_solver linsys_solver;

// Prototypes for solution
extern c_float xsolution[8];
extern c_float ysolution[16];

extern OSQPSolution solution;

// Prototype for info structure
extern OSQPInfo info;

// Prototypes for the workspace
extern c_float work_rho_vec[16];
extern c_float work_rho_inv_vec[16];
extern c_float work_x[8];
extern c_float work_y[16];
extern c_float work_z[16];
extern c_float work_xz_tilde[24];
extern c_float work_x_prev[8];
extern c_float work_z_prev[16];
extern c_float work_Ax[16];
extern c_float work_Px[8];
extern c_float work_Aty[8];
extern c_float work_delta_y[16];
extern c_float work_Atdelta_y[8];
extern c_float work_delta_x[8];
extern c_float work_Pdelta_x[8];
extern c_float work_Adelta_x[16];
extern c_float work_D_temp[8];
extern c_float work_D_temp_A[8];
extern c_float work_E_temp[16];

extern OSQPWorkspace workspace;

#endif // ifndef WORKSPACE_H
